# Generated by Django 4.2.7 on 2023-11-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tools',
            options={'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
    ]
