# Generated by Django 4.2.4 on 2023-12-07 09:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_tools_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tools",
            name="photos",
        ),
        migrations.AddField(
            model_name="tools",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="photo"
            ),
        ),
    ]
