# Generated by Django 4.2.7 on 2023-11-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_sub_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_name',
        ),
    ]
