# Generated by Django 4.2.7 on 2023-11-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
