# Generated by Django 4.2.7 on 2023-11-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_sub_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
    ]
