# Generated by Django 4.2.7 on 2023-12-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_photo_options_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='photos',
        ),
        migrations.AddField(
            model_name='tools',
            name='photos',
            field=models.ManyToManyField(to='core.photo'),
        ),
    ]
