# Generated by Django 4.2.7 on 2023-11-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tools_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='photos',
        ),
        migrations.AddField(
            model_name='tools',
            name='photos',
            field=models.ImageField(default=1, upload_to='', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
