# Generated by Django 4.2.7 on 2023-11-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_tools_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
