# Generated by Django 4.2.7 on 2023-11-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tools_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='photos',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
