# Generated by Django 4.2.7 on 2023-11-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subcategory'),
            preserve_default=False,
        ),
    ]
