# Generated by Django 4.2.7 on 2023-11-27 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_category_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
