# Generated by Django 4.2.7 on 2023-11-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_category_sub_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='sub_name',
        ),
    ]
