# Generated by Django 4.2.7 on 2023-11-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_name_subcategory_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='sub_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
