# Generated by Django 4.2.7 on 2023-11-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_subcategory_sub_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_name',
            new_name='name',
        ),
    ]
