# Generated by Django 4.2.7 on 2023-11-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_sub_name_subcategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_name',
            new_name='subcategory',
        ),
    ]
