# Generated by Django 4.2.7 on 2023-11-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_category_subcategory_subcategory_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': ('Подкатегории', 'Категории')},
        ),
    ]
