# Generated by Django 4.2.7 on 2023-11-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
